# Generated by Django 4.2.6 on 2023-10-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.IntegerField()),
                ('Other', models.IntegerField()),
                ('Food', models.IntegerField()),
                ('Transport', models.IntegerField()),
                ('Apparel', models.IntegerField()),
                ('Education', models.IntegerField()),
                ('Grocery', models.IntegerField()),
                ('Health', models.IntegerField()),
                ('Others', models.IntegerField()),
            ],
        ),
    ]
