# Generated by Django 4.2.6 on 2023-10-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Other',
            new_name='Other_Expense',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='Others',
            new_name='Other_Income',
        ),
    ]
