# Generated by Django 4.2.6 on 2023-11-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='User',
            new_name='user',
        ),
    ]
