# Generated by Django 4.2.6 on 2023-11-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
