# Generated by Django 4.2.6 on 2023-12-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_alter_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='username',
        ),
    ]
