# Generated by Django 4.2.6 on 2023-12-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
